name: Reviewer Lottery

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]
    branches:
      - main
      - maintenance/**
      - beta/**

jobs:
  addReviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uesteibar/reviewer-lottery@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
