name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
      - maintenance/**
      - beta/**
  pull_request:
    branches:
      - main
      - maintenance/**
      - beta/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      # Can't use npm ci, because it fails on missing optional dependencies
      - run: npm install

      # Build
      - name: Build
        run: npm run build

      # Run linting
      - name: Lint
        run: npm run lint

      # Runs tests
      - name: Test
        run: npm run test.ci

  prComment:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: 'Demo will be published at https://apps.inindca.com/common-ui-docs/genesys-webcomponents/${{ github.head_ref}}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
