name: UX Review

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  uxReview:
    if: github.event.label.name == 'ux review'
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: "🧐 UX Reviewers Assemble!\n
              - @conor-darcy\n
              - @Igaenssley\n
              - @mattgaughran\n
              - @stephenim\n
            \n
            Review Reminders\n
              1. Add a comment to let us know who is reviewing this change\n
              2. Check out the implementation @ https://apps.inindca.com/common-ui-docs/genesys-webcomponents/${{ github.head_ref }}\n
              3. Be sure to note which issues are blockers and which are refinements
          "
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          